package com.rpgcornerteam.rpgcorner.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisposeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposeAllPropertiesEquals(Dispose expected, Dispose actual) {
        assertDisposeAutoGeneratedPropertiesEquals(expected, actual);
        assertDisposeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposeAllUpdatablePropertiesEquals(Dispose expected, Dispose actual) {
        assertDisposeUpdatableFieldsEquals(expected, actual);
        assertDisposeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposeAutoGeneratedPropertiesEquals(Dispose expected, Dispose actual) {
        assertThat(expected)
            .as("Verify Dispose auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposeUpdatableFieldsEquals(Dispose expected, Dispose actual) {
        assertThat(expected)
            .as("Verify Dispose relevant properties")
            .satisfies(e -> assertThat(e.getDisposeDate()).as("check disposeDate").isEqualTo(actual.getDisposeDate()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisposeUpdatableRelationshipsEquals(Dispose expected, Dispose actual) {
        // empty method
    }
}
